server:
  port: 4040
---
environments: development
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowopendev
    username: developer
    password: developer
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: flowoopenv@gmail.com
    password: tpzrgkhfrvcxtccf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"

---
environments: test
server:
  port: 3030
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: testdb
    password: psw1234
  jpa:
    database: H2
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: f4kemailt3st@gmail.com
    password: pospmwcwuqdkjjhb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true