environment: development
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowopendev
    username: developer
    password: developer
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop

---
environment: test
server:
  port: 3030
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: testdb
    password: psw1234
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: none