spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowopendev
    username: root
    password: password_root
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop