server:
  port: 4040
---
environments: development
server:
  port: 8080
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/flowopendev
    username: developer
    password: developer
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
      output:
        ansi:
          enabled: ALWAYS
      mail:
        host: smtp.gmail.com
        port: 587
        username: f4kemailt3st@gmail.com
        password: pospmwcwuqdkjjhb
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
---
environments: test
server:
  port: 3030
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: flowoopenv@gmail.com
    password: tpzrgkhfrvcxtccf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
